export const SET_ERROR = 'SET_ERROR'
export const HIDE_ERROR = 'HIDE_ERROR'

export const SET_NOTIFICATION = 'SET_NOTIFICATION'
export const HIDE_NOTIFICATION = 'HIDE_NOTIFICATION'

export const GET_CARDS_REQUEST = 'GET_CARDS_REQUEST'
export const GET_CARDS_SUCCESS = 'GET_CARDS_SUCCESS'
export const GET_CARDS_FAILURE = 'GET_CARDS_FAILURE'

export const GET_READS_REQUEST = 'GET_READS_REQUEST'
export const GET_READS_SUCCESS = 'GET_READS_SUCCESS'
export const GET_READS_FAILURE = 'GET_READS_FAILURE'

export const GET_MY_READS_REQUEST = 'GET_MY_READS_REQUEST'
export const GET_MY_READS_SUCCESS = 'GET_MY_READS_SUCCESS'
export const LOAD_READ = 'LOAD_READ'
export const GET_MY_READS_FAILURE = 'GET_MY_READS_FAILURE'
export const GET_USER_PREF_REQUEST = 'GET_USER_PREF_REQUEST'
export const GET_USER_PREF_SUCCESS = 'GET_USER_PREF_SUCCESS'
export const GET_USER_PREF_FAILURE = 'GET_USER_PREF_FAILURE'

export const GET_CUSTOM_READ_REQUEST = 'GET_CUSTOM_READ_REQUEST'
export const GET_CUSTOM_READ_SETUP_SUCCESS = 'GET_CUSTOM_READ_SETUP_SUCCESS'
export const ADD_CARD_TO_READ = 'ADD_CARD_TO_READ'
export const REMOVE_CARD_FROM_READ = 'REMOVE_CARD_FROM_READ'
export const REVERSE_CARD = 'REVERSE_CARD'
export const FLIP_CARD = 'FLIP_CARD'
export const CREATE_READING_CARDS = 'CREATE_READING_CARDS'
export const GET_CUSTOM_READ_FAILURE = 'GET_CUSTOM_READ_FAILURE'
export const CLEAR_READ = 'CLEAR_READ'
export const ADD_READ_PREF = 'ADD_READ_PREF'

export const START_SESSION = 'START_SESSION'
